import { StockConfig } from "./config";

interface AlertResult {
  success: boolean;
  issueUrl?: string;
}

export async function createAlert(
  stock: StockConfig,
  price: number,
  type: "BUY" | "SELL"
): Promise<AlertResult> {
  const githubToken = process.env.GITHUB_TOKEN;
  const githubRepo = process.env.GITHUB_REPO;

  if (!githubToken || !githubRepo) {
    console.error("[notifications] GITHUB_TOKEN or GITHUB_REPO not configured");
    return { success: false };
  }

  const threshold =
    type === "BUY" ? stock.lowerThreshold : stock.upperThreshold;
  const action = type === "BUY" ? "below" : "above";
  const recommendation =
    type === "BUY"
      ? `${stock.name} is trading below the buy threshold of $${stock.lowerThreshold}. Consider buying.`
      : `${stock.name} is trading above the sell threshold of $${stock.upperThreshold}. Consider selling.`;

  const title = `🚨 [${stock.symbol}] ${type} Signal: $${price.toFixed(2)}`;
  const body = `## ${type} Signal for ${stock.name} (${stock.symbol})

| Detail | Value |
|--------|-------|
| **Current Price** | $${price.toFixed(2)} |
| **${type} Threshold** | $${threshold} |
| **Status** | Price is ${action} threshold |
| **Time** | ${new Date().toISOString()} |

### Recommendation

${recommendation}

### Thresholds

- Buy Zone: < $${stock.lowerThreshold}
- Sell Zone: > $${stock.upperThreshold}

---
*Generated by Stock Monitor*`;

  try {
    const response = await fetch(
      `https://api.github.com/repos/${githubRepo}/issues`,
      {
        method: "POST",
        headers: {
          Authorization: `token ${githubToken}`,
          Accept: "application/vnd.github.v3+json",
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          title,
          body,
          labels: [
            type === "BUY" ? "buy-signal" : "sell-signal",
            stock.symbol.toLowerCase(),
          ],
        }),
      }
    );

    if (!response.ok) {
      const errorText = await response.text();
      console.error(`[notifications] GitHub API error (${response.status}):`, errorText);
      return { success: false };
    }

    const data = await response.json();
    console.log(`[notifications] Issue created: ${data.html_url}`);
    return { success: true, issueUrl: data.html_url };
  } catch (error) {
    console.error("[notifications] Failed to create GitHub issue:", error);
    return { success: false };
  }
}
